//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE_MISSION3
{
    using System;
    using System.Collections.Generic;
    
    public partial class rapport
    {
        public rapport()
        {
            this.offrirs = new HashSet<offrir>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string motif { get; set; }
        public string bilan { get; set; }
        public string idVisiteur { get; set; }
        public int idMedecin { get; set; }
    
        public virtual medecin medecin { get; set; }
        public virtual ICollection<offrir> offrirs { get; set; }
        public virtual visiteur visiteur { get; set; }
    }
}
