//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE_MISSION3
{
    using System;
    using System.Collections.Generic;
    
    public partial class visiteur
    {
        public visiteur()
        {
            this.rapports = new HashSet<rapport>();
        }
    
        public string id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public string adresse { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
        public Nullable<System.DateTime> dateEmbauche { get; set; }
    
        public virtual ICollection<rapport> rapports { get; set; }
    }
}
